name: Test and Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Node ${{ matrix.node-version }} Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        redis-version: [6]
        mongodb-version: ['5.0']

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
        env:
          CI: true

      - name: Run coverage
        if: matrix.node-version == '18.x'
        run: |
          pnpm coverage
        env:
          CI: true

      - name: Upload coverage artifacts
        if: matrix.node-version == '18.x'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.lcov

  coverage:
    name: Upload Coverage
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: coverage.lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
